apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-server
  template:
    metadata:
      labels:
        run: demo-server
    spec:
      containers:
      - name: demo-server
        image: quay.io/avni16/demo:v1
        ports:
          - containerPort: 8080

